{% set name = "pefile" %}
{% set version = "2022.5.30" %}
{% set hash = "a5488a3dd1fd021ce33f969780b88fe0f7eebb76eb20996d7318f307612a045b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - future

test:
  imports:
    - pefile
    - peutils
    - ordlookup

about:
  home: https://github.com/erocarrera/pefile
  license: MIT
  license_file: LICENSE
  summary: pefile is a Python module to read and work with PE (Portable Executable) files

extra:
  recipe-maintainers:
    - nicoddemus
