{% set name = "pefile" %}
{% set version = "2021.5.24" %}
{% set hash = "ed79b2353daa58421459abf4d685953bde0adf9f6e188944f97ba9795f100246" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - future

test:
  imports:
    - pefile
    - peutils
    - ordlookup

about:
  home: https://github.com/erocarrera/pefile
  license: MIT
  license_file: LICENSE
  summary: pefile is a Python module to read and work with PE (Portable Executable) files

extra:
  recipe-maintainers:
    - nicoddemus
