travis:
  secure:
    BINSTAR_TOKEN: S5bjuSZ/PNqLw7YdiawaRlopgwduVCzCttQladQPepTwVF+XcyCjUQWhmquaiot5Hlls1QRzAIYoskFTXeaOgTETCFZiDR0OamnoCqn6S5p/YJpbGQZIqInGZxgH/1lgppCaYXW33E97F7fRG4Z0MJpyRbA3tbeOu2QbJeaZcFkf4+2W+6sWLM1+hGBnyM38cRlL9kk9euKg473rHDurQigAWVAOhVPblim4qT8KKvo3x092WG/JPjkE1fDEBdMOs8evyqHLbifh+y++0QFL9Df7nGL+U3Ps95gCJUuFzrUqmSIU5S8xxVTptoSiNtnBCbuJuDT0obHD0jvt/1ZVxeyNZwyoN1nHzxnmRciR1m3Wfr5t4+K/fJKtzcVeki4ZWrXkc6JN+xLau/7EG9wsbL6e4ozbURwsVcOtwvFZE5K1BQdO2x99z2AsOHgobN4kSyKQDaTmhF+/ub9Ny6UyAayWK9m0Tj+a0ojFFFTQy9pzp2SLxk+7/VbeOI964sUX/krmOG5YSdx62aZzUmsiSqwNXMXy2wExKXTV+UzqgytLwKChaZ3UYfIEFxqZZsEvsH7R0lWiCAAMczw9jxtb+LN6E1/ugQ72gR4l5EH2gmXQd0ljSH6JalHE/NxK0sa5MzZmoF2TmkGXdYkTOz+JDKUXUPXA/ljOm9G/fTtbxIg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
